import type { NextConfig } from "next";
import { ALL_REDIRECTS } from "./lib/redirects";

// Security headers — Phase-1-Plan "SEO Must-Haves" (B3).
// Applied globally to every route via headers().
const securityHeaders = [
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
  { key: "X-DNS-Prefetch-Control", value: "on" },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders,
      },
    ];
  },
  // Legacy WordPress → new-site redirects (B10).
  // Source of truth: lib/redirects.ts (generated by scripts/generate-redirects.py).
  async redirects() {
    return ALL_REDIRECTS;
  },
};

export default nextConfig;
