/**
 * WordPress-migrated FAQs — generated by scripts/migrate-faqs.py.
 *
 * DO NOT HAND-EDIT. Re-running the migration script overwrites this
 * file. For hand-kuratierte FAQs use content/faqs-curated.ts.
 * content/faqs.ts aggregates both.
 *
 * published=false + needsReview=true means the imported FAQ
 * contradicts our D9 truth-alignment (active handicap claims).
 * Decision per FAQ: rewrite honestly in faqs-curated.ts, or drop.
 */

import type { FaqItem } from "@/lib/faqs/types";

export const WP_FAQS: FaqItem[] = [
  {
    slug: "laeuft-die-mitgliedschaft-fuer-ein-kalenderjahr-1-1-31-12-oder-fuer-ein-jahr-ab-",
    question: `Läuft die Mitgliedschaft für ein Kalenderjahr (1.1.-31.12.) oder für ein Jahr ab Eintrittsdatum?`,
    answer: `Die Mitgliedschaft läuft ab dem vom Mitglied gewünschten Eintrittsdatum , z.B. dem 10. Juni 2012 für mindestens 12 Monate, die wir im Normalfall auf das Monatsende des folgenden Monat aufrunden.

Man kann jederzeit einsteigen und zwölf Monate in Folge Golf spielen.

Schließlich ist immer irgendwo gerade Saison.`,
    category: "mitgliedschaft",
    published: true,
    wpId: "174",
  },
  {
    slug: "wie-kann-ich-mitglied-werden",
    question: `Wie kann ich Mitglied werden?`,
    answer: `Bitte fülle das Anmeldeformular unter Mitglied werden! aus oder schickt Eure Daten per E-Mail.

Benötigt werden:


- Name - der auf der Clubkarte angedruckt wird

- Eigene E-Mail-Adresse - die länger als ein Jahr bestand haben wird.


- Berufliche Adressen ändern sich häufiger als man denkt.

- Für die allgemeinem begrenzte Kommunikation während der Mitgliedschaft

- Zur Erinnerung zwecks möglicher Verlängerung nach einem Jahr.


- Dein aktuelles Handicap - das Du auf den Platz bringen möchtest.

- Postanschrift zum Versand der Karte

- Das gewünschte Startdatum - auf dem dann das Enddatum der Fernmitgliedschaft basiert

- Sonderwünsche (optinal)`,
    category: "mitgliedschaft",
    published: true,
    wpId: "183",
  },
  {
    slug: "wie-kann-ich-die-mitgliedschaft-verlaengern",
    question: `Wie kann ich die Mitgliedschaft verlängern?`,
    answer: `Bitte fülle das Formular unter Mitgliedschaft verlängern aus oder schickt Eure aktualisierten Daten per E-Mail.

Benötigt werden:


- Aktuelle E-Mail-Adresse - die länger als ein Jahr bestand haben wird.


- Berufliche Adressen ändern sich häufiger als man denkt.

- Für die allgemeinem begrenzte Kommunikation während der Mitgliedschaft

- Zur Erinnerung zwecks möglicher Verlängerung nach einem Jahr.


- Dein aktuelles Handicap - dass sich hoffentlich verbessert hat.

- Aktuelle Postanschrift - falls sich diese im Laufe der letzten 12 Monate geändert hat

- Das Datum der Verlängerung - falls Ihr mal bis zum nächsten Frühling warten wollt

- Sonderwünsche (optional)`,
    category: "mitgliedschaft",
    published: true,
    wpId: "391",
  },
  {
    slug: "wie-kann-ich-die-mitgliedschaft-kuendigen",
    question: `Wie kann ich die Mitgliedschaft kündigen?`,
    answer: `Eine Kündigung ist nicht notwendig, da die Mitgliedschaft prinzipiell nur für ein Jahr abgeschlossen wird und es keine automatische Verlängerung gibt.

Rechtzeitig vor Ablauf der Mitgliedschaft schreiben wir die Mitglieder 1-2 Mal per E-Mail an und wenn es keine Rückmeldung gibt, endet die Mitgliedschaft zum Enddatum dass auf der Clubkarte angedruckt ist.

Falls ihr trotzdem schriftlich kündigen wollt, dann scheibt einfach eine E-Mail.`,
    category: "mitgliedschaft",
    published: true,
    wpId: "394",
  },
  {
    slug: "wie-sieht-die-clubkarte-aus-aus-welchem-material-ist-sie",
    question: `Wie sieht die Clubkarte aus? Aus welchem Material ist sie?`,
    answer: `[fusion_builder_container hundred_percent="no" equal_height_columns="no" menu_anchor="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" background_color="" background_image="" background_position="center center" background_repeat="no-repeat" fade="no" background_parallax="none" parallax_speed="0.3" video_mp4="" video_webm="" video_ogv="" video_url="" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" overlay_color="" video_preview_image="" border_size="" border_color="" border_style="solid" padding_top="" padding_bottom="" padding_left="" padding_right=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" background_position="left top" background_color="" border_size="" border_color="" border_style="solid" border_position="all" spacing="yes" background_image="" background_repeat="no-repeat" padding="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="small-visibility,medium-visibility,large-visibility" center_content="no" last="no" min_height="" hover_type="none" link=""][fusion_text]
Die Clubkarte


- ist aus demselben Plastikmaterial einer Kreditkarte

- hat die exakte DIN-Größe einer Kreditkarte

- ist vorne und hinten hochwertig farbig bedruckt

- Name, Datum und Hcp sind in Gold auf die Vorderseite gedruckt

- ein Unterschriftsfeld auf der Rückseite für das Mitglied

- das Logo des Thailändischen Golfverbandes

Wir haben der Karte ein cooles, professionelles Design gegeben damit es Spaß macht Sie im Club-Sekretariat lässig auf den Tresen zu legen.

So sieht die Karte für die Saison 2012/2013, die seit dem April 2012 zum Einsatz kommt:

[caption id="attachment_330" align="alignnone" width="357"] Vorderseite der Mitgliedskarte[/caption]



[caption id="attachment_329" align="alignnone" width="300"] Rückseite der Mitgliedskarte[/caption]
Vorgängerkarte
Aus Gründen der Nostalgie die Vorgängerkarte:

[caption id="attachment_849" align="alignnone" width="250"] Alte Mitgliedskarte - Front[/caption]



[caption id="attachment_847" align="alignnone" width="180"] Alte Mitgliedskarte - Back[/caption]

[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]`,
    category: "karte",
    published: true,
    wpId: "177",
  },
  {
    slug: "wie-lange-dauert-es-bis-die-clubkarte-bei-mir-eintrifft",
    question: `Wie lange dauert es bis die Clubkarte bei mir eintrifft?`,
    answer: `Die Kartenrohlinge liegen zum Bedrucken bereit. Nach Zahlungseingang gehen in der Regel einmal die Woche die neuen Karten i
n die Post.

Der Postweg aus Deutschland dauert 1-2 Tage innerhalb Deutschlands und etwas länger nach Österreich und in die Schweiz.`,
    category: "karte",
    published: true,
    wpId: "179",
  },
  {
    slug: "wie-ist-der-prinzipielle-ablauf-der-handicap-verwaltung-der-fernmitgliedschaft",
    question: `Wie ist der prinzipielle Ablauf der Handicap-Verwaltung der Fernmitgliedschaft?`,
    answer: `Du schickst uns die Basisdaten Deines „Heimatclubs“ in der Nähe und eventuell noch ein, zwei, drei weiterer Clubs zu, die Du wahrscheinlich bespielen wirst, damit wir diese in unserem Handicapsystem vorher erfassen. Weitere Kurse erfassen wir nach Bedarf.

Aktuell befinden sich ca. 170 Kurse im System

Zu den Kursen reichen ein Link zur Unterseite des Clubs auf der die Scorekarte zu sehen ist. Slope und/oder CR-Werte kann man sich aus einem Portal wie www.1.golf.eu ziehen, falls diese Werte nicht sowieso schon auf der Scorekarte sind.

Zum Beispiel der "Golfclub Seefeld-Wildmoos" in Österreich
Seefeldgolf.com Scorekarte
http://www.1golf.eu/club/golfclub-seefeld-wildmoos/

Oder eine Digitalfotografie einer Scorekarte oder den Link zur Online-Scorekarte des jeweiligen Golfclubs.

Leider können die Mitglieder noch keine Kurse online erfassen.

Deine jeweiligen Ergebnisse Deiner Runden kannst Du dann Online in unserem Mitgliederbereich selber erfassen und nach 5 übermittelten Scorekarten und nach Ablauf eines jeweiligen Kalendermonats gibt es das erste Update auf das Handicap.

Der Spaß am eigenen Handicap soll dabei im Vordergrund steht. Da wir nach USGA-Regeln berechnen, gibt es diverse Möglichkeiten Ergebnisse für das eigene Handicap zu erfassen. Diese sind:


- 18- Loch und/oder 9 Loch

- Turniere

- Reguläre Runden auf den Heimatclubs

- Sogenannte Auswärtsrunden auf fremden Kursen

- Sonstige Informationen

Einmal im Monat oder öfter wird das Handicap neu berechnet und ist Online ersichtlich.

Ab der Saison 2012 bekommst Du bekommst auf Anfrage Dein Handicap-Zertifikat mit Deinem neuen, aktuellen Handicap per E-Mail zugeschickt. Online kannst Du Dir jederzeit eine Handicapkarte herunterladen, ausdrucken und mit der Clubkarte mitführen.

In Ausnahmefällen können wir ein Handicap auch einmal öfter oder über einen längeren Zeitraum neu berechnen z.B. um die ersten 5 Runden zusammen zu bekommen oder um ein „Spanien-Handicap“ von 36 zu erhalten.

Gegen eine Gebühr von 5 Euro wird bei Bedarf eine neue Karte mit aktualisiertem Handicap ausgestellt und versandt.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "215",
  },
  {
    slug: "wie-uebermittle-ich-mein-erstes-handicap-bzw-meine-platzreife",
    question: `Wie übermittle ich mein erstes Handicap bzw. meine Platzreife?`,
    answer: `Auf der Clubkarte wird das Handicap angedruckt, das bei der Anmeldung im Formular eintragen wurde. Natürlich können Sie mir gerne Ihren Handicap-Nachweis einscannen und per E-Mail zukommen lassen oder zufaxen.

Es gibt alle 12 Monate eine aktualisierte Clubkarte.

Auf Anfrage und gegen eine Gebühr von 5 Euro stellen wir auf Anfrage gerne auch eine zusätzliche Clubkarte innerhalb der Mitgliedschaft aus.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "217",
  },
  {
    slug: "wer-braucht-ein-aktuelles-handicap",
    question: `Wer braucht ein aktuelles Handicap?`,
    answer: `Golfer, die …


- Turniere spielen und etwas gewinnen möchten

- Spaß an Statistiken und einem persönlichen Leistungsmesser haben

- auf bestimmten Golfkursen spielen möchten, die ein bestimmtes Handicap erfordern, wenn z.B. am Wochenende ein Hcp 36 erforderlich ist

- in Ländern spielen wie Spanien spielen möchten wo Hcp 28 oder Hcp 36 erforderlich sein kann

Die offiziellen Vorgaben der Kurse sind erst einmal "streng", vor Ort wird nach aktuell Tagesauslastung entschieden.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "219",
  },
  {
    slug: "was-ist-ein-recreational-hcp-wie-unterscheidet-es-sich-vom-hcp-des-dgv",
    question: `Was ist ein Recreational-Hcp? Wie unterscheidet es sich vom Hcp des DGV?`,
    answer: `Wir Deutschen, Österreicher und Schweizer nehmen unser Handicap bierernst und wenn wir Glück haben, spielen wir in jedem Turnier mit dem gefühlten Regelwart des Clubs im selben Flight.

Im angelsächsischem Raum, dem Einzugsgebiet der USGA und dem Rest der Welt ist es etwas entspannter, da nicht nur Turniere und Extra-Day-Scores ins Hcp einfließen, sondern beim Recreational-Handicap grundsätzlich alle Runden hinzugezählt werden können

So kommt jeder zu seinem Handicap  und muss nicht auf Hcp 54 hängen blieben, weil er keine Turniere spielt. Der Spaß an der Statistik und der Messung der eigenen Leistung steht hier im Vordergrund.

Einbezogen werden


- Turniere

- Heimrunden

- Auswärtsrunden

- 18er-Runden

- 9er-Runden

- Sonnenrunden

- Regenrunden

- Sch...

- ...`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "221",
  },
  {
    slug: "wie-bekomme-ich-ein-fortlaufendes-handicap",
    question: `Wie bekomme ich ein fortlaufendes Handicap?`,
    answer: `- durch Teilnahme an Turnieren oder vorgabewirksame Runden.

- durch Berechnung des Handicaps nur für den Eigengebrauch zum Beispiel in einer Excel-Tabelle.

- durch Anmeldung bei einem Drittanbieter, der Handicaps verwaltet. Weit verbreiteter Fall in Großbritannien.

oder


- Online beim Oakwoodgolfclub.de. Hier kannst Du unsere Handicapverwaltung testen

- Bei uns können ALLE! Runden ins Handicap einfließen.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "223",
  },
  {
    slug: "wie-werden-handicaps-berechnet",
    question: `Wie werden Handicaps berechnet?`,
    answer: `Unterschiedlich. Wir berechnen Handicaps nach den Vorgaben der USGA/TGA, die sich vom DGV und ÖGV leicht unterscheiden.

Das ist aber nicht weiter schlimm, da sich der Unterschied nach einer gewissen Anzahl eingereichter Scorekarten angleicht.

Unsere Handicap-Software erklärt sehr gut wie die Handicaps berechnet werden. Gerne schicken wir Dir diese Infos auf Anfrage zu.

Hartgesottene Zeitgenossen können sich auch auf den Seite der USGA mit der Handicapberechnung befassen.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "227",
  },
  {
    slug: "wie-bekomme-ich-einen-aktuellen-handicap-nachweis",
    question: `Wie bekomme ich einen aktuellen Handicap-Nachweis?`,
    answer: `Auf Anfrage bekommst Du einmal im Monat ein Update auf Dein Handicap in Abhängigkeit von der Anzahl der eingereichtenErgebnisse. Wir verschicken das Handicap-Zertifikat als PDF an Deine E-Mail-Adresse.`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "229",
  },
  {
    slug: "wie-kommen-die-golfclubs-in-die-handicapverwaltung",
    question: `Wie kommen die Golfclubs in die Handicapverwaltung?`,
    answer: `Wir müssen zuerst die Golfclubs, auf denen Du spielst einmal vorerfassen müssen, bevor Du Deine Scores selber erfassen kannst.

Dazu brauchen wir EINMAL die Daten zu jedem „Deiner“ Plätze, wenn diese nicht schon im System sind.

Am besten gleich mit einen Link zur Scorekarte des Golfkurses als Link
z.B. http://www.gc-dm.de/fuer-dein-spiel/

[caption id="attachment_1136" align="alignnone" width="300"] Scorekarte des GC Mommenheim[/caption]



und optional dessen Eintrag im Golfportal als Link
z.B. http://www.1golf.eu/club/golf-club-domtal-mommenheim-ev/

[caption id="attachment_405" align="alignnone" width="300"] GC Mommenheim auf 1golf.eu[/caption]

Oder schickt ein lesbares Handy-Foto der Score-Karte via E-Mail mit Betreff`,
    category: "handicap",
    published: false,
    needsReview: true,
    wpId: "400",
  },
  {
    slug: "wird-die-fernmitgliedschaft-von-anderen-clubs-in-deutschland-und-international-p",
    question: `Wird die Fernmitgliedschaft von anderen Clubs in Deutschland und international problemlos akzeptiert? Gibt es generell Probleme mit so "exotischen" Mitgliedschaften"?`,
    answer: `Du bist ein Greenfee-Spieler, der gerne unterschiedliche Plätze spielt und beruflich/privat oft unterwegs ist? Immer mit dem Golfbag im Kofferraum oder Fluggepäck? Mit der Fernmitgliedschaft kannst Du in Deutschland, Österreich, Schweiz, Frankreich, Portugal, Spanien, Irland, Ägypten und sonst wo auf der Welt spielen.

Viele unserer Mitglieder spielen seit Jahren mit einer Fernmitgliedschaft und haben in der Regel keine Probleme auf den Platz zu kommen.

99% der Clubs sind als Wirtschaftsunternehmen daran interessiert Geld über Greenfees einzunehmen.

1% der Clubs ist bewusst elitär und öffnet sich nur ihren Mitgliedern und begrenzt deren Gästen.`,
    category: "akzeptanz",
    published: true,
    wpId: "231",
  },
  {
    slug: "wird-die-mitgliedschaft-vom-oesterreichischen-golfverband-anerkannt-kann-man-ueb",
    question: `Wird die Mitgliedschaft vom Österreichischen Golfverband anerkannt / kann man überall in Österreich spielen?`,
    answer: `Wir haben knapp 50% unserer Mitglieder im schönen Österreich, davon einige schon seit mehreren Jahren.
Nach meiner Schätzung sind > 95% der Plätze in Österreich mit der Fernmitgliedschaft bespielbar.`,
    category: "akzeptanz",
    published: true,
    wpId: "1065",
  },
  {
    slug: "wo-kommen-die-mitglieder-her",
    question: `Wo kommen die Mitglieder her?`,
    answer: `[fusion_builder_container hundred_percent="no" equal_height_columns="no" menu_anchor="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" background_color="" background_image="" background_position="center center" background_repeat="no-repeat" fade="no" background_parallax="none" parallax_speed="0.3" video_mp4="" video_webm="" video_ogv="" video_url="" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" overlay_color="" video_preview_image="" border_size="" border_color="" border_style="solid" padding_top="" padding_bottom="" padding_left="" padding_right=""][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" background_position="left top" background_color="" border_size="" border_color="" border_style="solid" border_position="all" spacing="yes" background_image="" background_repeat="no-repeat" padding="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="small-visibility,medium-visibility,large-visibility" center_content="no" last="no" min_height="" hover_type="none" link=""][fusion_text]



Die Mitglieder des Golfclubs kommen gegenwärtig aus mehrheitlich aus Deutschland, Österreich, Schweiz und natürlich Thailand. Es gab/gibt aber auch Exoten in Brasilien, Italien, England, Dänemark und Indien

Auf der Karte habe ich die Mitglieder mit Mitgliedsnummer, Vornamen und teilweise dem aktuellen Enddatum der Mitgliedschaft (teilweise) eingetragen.



[/fusion_text][fusion_code]Jmx0O2lmcmFtZSBzcmM9JnF1b3Q7aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9tYXBzL2QvZW1iZWQ/bWlkPTFocEFsNXpIX2p1bUk4RUE0b0tvQ0xsS2lsNzgmcXVvdDsgd2lkdGg9JnF1b3Q7MTAwJSZxdW90OyBoZWlnaHQ9JnF1b3Q7NDgwJnF1b3Q7Jmd0OyZsdDsvaWZyYW1lJmd0Ow==[/fusion_code][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]`,
    category: "mitglieder",
    published: true,
    wpId: "181",
  },
  {
    slug: "wieviele-mitglieder-hat-der-club-im-deutschsprachigen-raum",
    question: `Wieviele Mitglieder hat der Club im deutschsprachigen Raum?`,
    answer: `Im DACH-Raum sind es ca. 300 aktive Mitglieder.

Auf dieser Karte kann man sehen, wie sich die Mitglieder im DACH_Raum und darüber hinaus verteilen.`,
    category: "mitglieder",
    published: true,
    wpId: "396",
  },
];
