/**
 * Legacy WordPress → new-site redirect map.
 * Generated by scripts/generate-redirects.py from wordpress-exports/.
 *
 * DO NOT HAND-EDIT. Re-generate whenever a fresh WP export drops into
 * wordpress-exports/ and URL changes need to be reflected.
 *
 * Consumed by next.config.ts → async redirects(). All entries are
 * permanent (308) by default. Next.js automatically handles both
 * trailing-slash and non-trailing-slash variants of the source path.
 */

export type RedirectEntry = {
  source: string;
  destination: string;
  permanent: boolean;
};

/** Pages — hand-curated per category mapping in the generator. */
export const PAGE_REDIRECTS: RedirectEntry[] = [
  { source: "/blog-zur-fernmitgliedschaft-im-golfclub/", destination: "/blog", permanent: true },
  { source: "/blog-zur-fernmitgliedschaft-im-golfclub/golfbuddy-golfuhr-fuer-fernmitgliedschaft/", destination: "/blog", permanent: true },
  { source: "/blog-zur-fernmitgliedschaft-im-golfclub/worldhandicap-sytem-whs/", destination: "/faq#was-ist-ein-recreational-hcp-wie-unterscheidet-es-sich-vom-hcp-des-dgv", permanent: true },
  { source: "/faq-fragen-zur-fernmitgliedschaft/", destination: "/faq", permanent: true },
  { source: "/fuer-wen-lohnt-sich-eine-fernmitgliedschaft/", destination: "/mitglied-werden", permanent: true },
  { source: "/golfclub/fernmitgliedschaft-im-golfclub-beantragen/", destination: "/mitglied-werden", permanent: true },
  { source: "/golfclub/fernmitgliedschaft-im-golfclub-beantragen/10-euro-werbepraemie/", destination: "/faq#gibt-es-ein-auto-renewal", permanent: true },
  { source: "/golfclub/fernmitgliedschaft-im-golfclub-beantragen/143-euro-per-flight-fuer-4-freunde/", destination: "/mitglied-werden", permanent: true },
  { source: "/golfclub/fernmitgliedschaft-im-golfclub-beantragen/55-euro-fuer-ein-jahr-fernmitgliedschaft/", destination: "/mitglied-werden", permanent: true },
  { source: "/golfclub/fernmitgliedschaft-im-golflcub-verlaengern/", destination: "/mitgliedschaft-verlaengern", permanent: true },
  { source: "/golfclub/google-maps-mitglieder/", destination: "/ueber-uns", permanent: true },
  { source: "/golfclub/handicapverwaltung-testen/", destination: "/faq#warum-aktuell-keine-handicap-verwaltung", permanent: true },
  { source: "/golfclub/links-zum-thema-golf/", destination: "/blog", permanent: true },
  { source: "/golfclub/scorekarte-erfassen-cloned-backup/", destination: "/faq", permanent: true },
  { source: "/golfclub/scorekarte-erfassen/", destination: "/faq#welche-app-fuer-scorecard-und-handicap-tracking", permanent: true },
  { source: "/home-2/", destination: "/", permanent: true },
  { source: "/info/", destination: "/ueber-uns", permanent: true },
  { source: "/info/agb/", destination: "/agb", permanent: true },
  { source: "/info/datenschutzerklaerung/", destination: "/datenschutz", permanent: true },
  { source: "/info/feedback-der-mitglieder/", destination: "/ueber-uns", permanent: true },
  { source: "/info/impressum/", destination: "/impressum", permanent: true },
  { source: "/info/kontakt/", destination: "/kontakt", permanent: true },
  { source: "/info/ueber-uns/", destination: "/ueber-uns", permanent: true },
  { source: "/products/", destination: "/mitglied-werden", permanent: true },
];

/** Blog posts — each WP /<slug>/ maps to /blog/<slug>. */
export const BLOG_POST_REDIRECTS: RedirectEntry[] = [
  { source: "/lieblingsclub-in-thailand/", destination: "/blog/lieblingsclub-in-thailand", permanent: true },
  { source: "/gedanken-beim-golf-42-handtuch-positiv/", destination: "/blog/gedanken-beim-golf-42-handtuch-positiv", permanent: true },
  { source: "/was-soll-man-trainieren/", destination: "/blog/was-soll-man-trainieren", permanent: true },
  { source: "/dgv-stetiges-wachstum-der-altesten-golfnation/", destination: "/blog/dgv-stetiges-wachstum-der-altesten-golfnation", permanent: true },
  { source: "/mygolf-app/", destination: "/faq#warum-aktuell-keine-handicap-verwaltung", permanent: true },
  { source: "/greenfees-als-ffernmitglied/", destination: "/blog/greenfees-als-ffernmitglied", permanent: true },
  { source: "/mitglieder-pro-land/", destination: "/blog/mitglieder-pro-land", permanent: true },
  { source: "/golfgeschichte-golf-im-20-jahrhundert/", destination: "/blog/golfgeschichte-golf-im-20-jahrhundert", permanent: true },
  { source: "/golfgeschichte-golf-im-19-jahrhundert/", destination: "/blog/golfgeschichte-golf-im-19-jahrhundert", permanent: true },
  { source: "/golfgeschichte-golf-im-15-und-16-jahrhundert/", destination: "/blog/golfgeschichte-golf-im-15-und-16-jahrhundert", permanent: true },
  { source: "/golfgeschichte-golf-im-17-und-18-jahrhundert/", destination: "/blog/golfgeschichte-golf-im-17-und-18-jahrhundert", permanent: true },
  { source: "/top-golfnationen/", destination: "/blog/top-golfnationen", permanent: true },
  { source: "/golfen-in-afghanistan/", destination: "/blog/golfen-in-afghanistan", permanent: true },
  { source: "/golf-fernmitgliedschaft-als-alternative/", destination: "/blog/golf-fernmitgliedschaft-als-alternative", permanent: true },
  { source: "/mscorecard-handicap-verwaltung-und-mehr/", destination: "/blog/mscorecard-handicap-verwaltung-und-mehr", permanent: true },
  { source: "/wie-das-bunkerspiel-verbessern/", destination: "/blog/wie-das-bunkerspiel-verbessern", permanent: true },
  { source: "/ideale-konfiguration-wedges-golfplatz/", destination: "/blog/ideale-konfiguration-wedges-golfplatz", permanent: true },
  { source: "/golf_ultimativer_sport_fuer_koerper_und_geist/", destination: "/blog/golf_ultimativer_sport_fuer_koerper_und_geist", permanent: true },
  { source: "/ki-generierte-golfbilder-amuesante-pannen-kreative-fehltritte/", destination: "/blog/ki-generierte-golfbilder-amuesante-pannen-kreative-fehltritte", permanent: true },
  { source: "/al-wilson-golfspiel-auf-einem-fliegenden-doppeldecker-wahnsinn-oder-meisterleistung/", destination: "/blog/al-wilson-golfspiel-auf-einem-fliegenden-doppeldecker-wahnsinn-oder-meisterleistung", permanent: true },
];

/** FAQ items — each WP /faq-items/<slug>/ maps to /faq#<slug>. */
export const FAQ_REDIRECTS: RedirectEntry[] = [
  { source: "/faq-items/lauft-die-mitgliedschaft-fur-ein-kalenderjahr-1-1-31-12-oder-fur-ein-jahr-ab-eintrittsdatum/", destination: "/faq#lauft-die-mitgliedschaft-fur-ein-kalenderjahr-1-1-31-12-oder-fur-ein-jahr-ab-eintrittsdatum", permanent: true },
  { source: "/faq-items/wie-sieht-die-clubkarte-aus-aus-welchem-material-ist-sie/", destination: "/faq#wie-sieht-die-clubkarte-aus-aus-welchem-material-ist-sie", permanent: true },
  { source: "/faq-items/wie-lange-dauert-es-bis-die-clubkarte-bei-mir-eintrifft/", destination: "/faq#wie-lange-dauert-es-bis-die-clubkarte-bei-mir-eintrifft", permanent: true },
  { source: "/faq-items/wo-kommen-die-mitglieder-her/", destination: "/faq#wo-kommen-die-mitglieder-her", permanent: true },
  { source: "/faq-items/wie-kann-ich-mitglied-werden/", destination: "/faq#wie-kann-ich-mitglied-werden", permanent: true },
  { source: "/faq-items/wie-ubermittle-ich-mein-erstes-handicap-bzw-meine-platzreife/", destination: "/faq#wie-ubermittle-ich-mein-erstes-handicap-bzw-meine-platzreife", permanent: true },
  { source: "/faq-items/wer-braucht-ein-aktuelles-handicap/", destination: "/faq#wer-braucht-ein-aktuelles-handicap", permanent: true },
  { source: "/faq-items/was-ist-ein-recreational-hcp-wie-unterscheidet-es-sich-vom-hcp-des-dgv/", destination: "/faq#was-ist-ein-recreational-hcp-wie-unterscheidet-es-sich-vom-hcp-des-dgv", permanent: true },
  { source: "/faq-items/wie-bekomme-ich-ein-fortlaufendes-handicap/", destination: "/faq#wie-bekomme-ich-ein-fortlaufendes-handicap", permanent: true },
  { source: "/faq-items/wie-werden-handicaps-berechnet/", destination: "/faq#wie-werden-handicaps-berechnet", permanent: true },
  { source: "/faq-items/wird-die-fernmitgliedschaft-von-anderen-clubs-in-deutschland-und-international-problemlos-akzeptiert-gibt-es-generell-probleme-mit-so-exotischen-mitgliedschaften/", destination: "/faq#wird-die-fernmitgliedschaft-von-anderen-clubs-in-deutschland-und-international-problemlos-akzeptiert-gibt-es-generell-probleme-mit-so-exotischen-mitgliedschaften", permanent: true },
  { source: "/faq-items/wie-kann-ich-die-mitgliedschaft-verlaengern/", destination: "/faq#wie-kann-ich-die-mitgliedschaft-verlaengern", permanent: true },
  { source: "/faq-items/wie-kann-ich-die-mitgliedschaft-kuendigen/", destination: "/faq#wie-kann-ich-die-mitgliedschaft-kuendigen", permanent: true },
  { source: "/faq-items/wie-viele-mitglieder-hat-ihr-club-zur-zeit-im-deutschsprachigen-raum/", destination: "/faq#wie-viele-mitglieder-hat-ihr-club-zur-zeit-im-deutschsprachigen-raum", permanent: true },
  { source: "/faq-items/wird-die-mitgliedschaft-vom-oesterreichischen-golfverband-anerkannt-kann-man-ueberall-in-oesterreich-spielen/", destination: "/faq#wird-die-mitgliedschaft-vom-oesterreichischen-golfverband-anerkannt-kann-man-ueberall-in-oesterreich-spielen", permanent: true },
];

/** All redirects merged — consumed by next.config.ts. */
export const ALL_REDIRECTS: RedirectEntry[] = [...PAGE_REDIRECTS, ...BLOG_POST_REDIRECTS, ...FAQ_REDIRECTS];
