/**
 * FAQ type-system. Data lives in content/faqs.ts (generated by
 * scripts/migrate-faqs.py from the WordPress export).
 */

export const FAQ_CATEGORIES = [
  "mitgliedschaft",
  "karte",
  "handicap",
  "akzeptanz",
  "mitglieder",
  "sonstiges",
] as const;

export type FaqCategory = (typeof FAQ_CATEGORIES)[number];

/** Display labels for each category. German, title-cased. */
export const CATEGORY_LABEL: Record<FaqCategory, string> = {
  mitgliedschaft: "Mitgliedschaft",
  karte: "Mitgliederkarte",
  handicap: "Handicap",
  akzeptanz: "Akzeptanz & Clubs",
  mitglieder: "Mitgliederzahl",
  sonstiges: "Sonstiges",
};

/** Display order — lower comes first on the FAQ page. */
export const CATEGORY_ORDER: Record<FaqCategory, number> = {
  mitgliedschaft: 1,
  karte: 2,
  akzeptanz: 3,
  mitglieder: 4,
  handicap: 5,
  sonstiges: 99,
};

export type FaqItem = {
  /** URL anchor slug, also stable ID for deep-linking. */
  slug: string;
  /** Question text — shown in summary + used for JSON-LD `name`. */
  question: string;
  /**
   * Answer text. Plain text + minimal Markdown (bullets as "- ", blank
   * lines between paragraphs). We render line-breaks as paragraph breaks
   * in the Accordion — no full Markdown parser here.
   */
  answer: string;
  /** Category for grouping + sidebar filter. */
  category: FaqCategory;
  /** Show in production? false = hidden from /faq AND JSON-LD. */
  published: boolean;
  /**
   * True when the imported WP content contradicts our truth-alignment
   * (active handicap claims). Human must decide rewrite vs. drop.
   * Always forces published=false by convention.
   */
  needsReview?: boolean;
  /** Optional: original WP post ID — handy for matching-back. */
  wpId?: string;
};
